"""
pdf_generator.py – Professional whitepaper-style PDF using ReportLab.
"""

import io
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    KeepTogether,
)
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


# ── Palette ───────────────────────────────────────────────────────────────────

INQ_DARK   = colors.HexColor("#0D1117")
INQ_BLUE   = colors.HexColor("#2563EB")
INQ_LIGHT  = colors.HexColor("#F8FAFC")
INQ_GRAY   = colors.HexColor("#64748B")
INQ_BORDER = colors.HexColor("#E2E8F0")
INQ_ACCENT = colors.HexColor("#7C3AED")


# ── Page callbacks ────────────────────────────────────────────────────────────

def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Header bar
    canvas.setFillColor(INQ_DARK)
    canvas.rect(0, h - 18 * mm, w, 18 * mm, fill=1, stroke=0)

    canvas.setFillColor(INQ_LIGHT)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(20 * mm, h - 11 * mm, "INQUIRA AI")
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(INQ_GRAY)
    canvas.drawRightString(w - 20 * mm, h - 11 * mm, "Research Report")

    # Footer
    canvas.setFillColor(INQ_BORDER)
    canvas.rect(0, 0, w, 12 * mm, fill=1, stroke=0)
    canvas.setFillColor(INQ_GRAY)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(20 * mm, 4.5 * mm,
                      f"Generated by Inquira AI  •  {datetime.now().strftime('%B %d, %Y')}")
    canvas.drawRightString(w - 20 * mm, 4.5 * mm, f"Page {doc.page}")

    canvas.restoreState()


# ── Style sheet ───────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "InqTitle",
            fontName="Helvetica-Bold",
            fontSize=26,
            textColor=INQ_DARK,
            spaceAfter=4 * mm,
            leading=32,
            alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "InqSubtitle",
            fontName="Helvetica",
            fontSize=13,
            textColor=INQ_GRAY,
            spaceAfter=6 * mm,
            leading=18,
        ),
        "meta": ParagraphStyle(
            "InqMeta",
            fontName="Helvetica",
            fontSize=9,
            textColor=INQ_GRAY,
            spaceAfter=2 * mm,
        ),
        "h2": ParagraphStyle(
            "InqH2",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=INQ_BLUE,
            spaceBefore=8 * mm,
            spaceAfter=3 * mm,
            leading=18,
        ),
        "h3": ParagraphStyle(
            "InqH3",
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=INQ_DARK,
            spaceBefore=5 * mm,
            spaceAfter=2 * mm,
        ),
        "body": ParagraphStyle(
            "InqBody",
            fontName="Helvetica",
            fontSize=10,
            textColor=INQ_DARK,
            leading=15,
            spaceAfter=4 * mm,
            alignment=TA_JUSTIFY,
        ),
        "bullet": ParagraphStyle(
            "InqBullet",
            fontName="Helvetica",
            fontSize=10,
            textColor=INQ_DARK,
            leading=15,
            spaceAfter=2 * mm,
            leftIndent=10 * mm,
            firstLineIndent=-4 * mm,
        ),
        "source_link": ParagraphStyle(
            "InqSourceLink",
            fontName="Helvetica",
            fontSize=9,
            textColor=INQ_BLUE,
            leading=14,
            spaceAfter=2 * mm,
            leftIndent=8 * mm,
        ),
        "source_title": ParagraphStyle(
            "InqSourceTitle",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=INQ_DARK,
            leading=14,
            spaceAfter=1 * mm,
            leftIndent=8 * mm,
        ),
    }
    return styles


# ── Markdown → Flowables ──────────────────────────────────────────────────────

def _md_to_flowables(md_text: str, styles: dict) -> list:
    """Convert simple markdown to ReportLab flowables."""
    flowables = []
    lines = md_text.split("\n")
    buffer = []

    def flush_buffer():
        if buffer:
            text = " ".join(buffer).strip()
            if text:
                # Inline bold: **text** → <b>text</b>
                text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
                flowables.append(Paragraph(text, styles["body"]))
            buffer.clear()

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("## "):
            flush_buffer()
            flowables.append(Paragraph(stripped[3:], styles["h2"]))
            flowables.append(HRFlowable(width="100%", thickness=0.5,
                                         color=INQ_BORDER, spaceAfter=2 * mm))
        elif stripped.startswith("### "):
            flush_buffer()
            flowables.append(Paragraph(stripped[4:], styles["h3"]))
        elif stripped.startswith(("- ", "* ", "• ")):
            flush_buffer()
            bullet_text = stripped[2:].strip()
            bullet_text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", bullet_text)
            flowables.append(Paragraph(f"• {bullet_text}", styles["bullet"]))
        elif re.match(r"^\d+\.\s", stripped):
            flush_buffer()
            text = re.sub(r"^\d+\.\s", "", stripped)
            text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
            flowables.append(Paragraph(f"• {text}", styles["bullet"]))
        elif stripped == "" or stripped == "---":
            flush_buffer()
            if stripped == "---":
                flowables.append(HRFlowable(width="100%", thickness=0.5,
                                             color=INQ_BORDER, spaceAfter=2 * mm))
        else:
            buffer.append(stripped)

    flush_buffer()
    return flowables


# ── Public API ────────────────────────────────────────────────────────────────

def generate_pdf(topic: str, report: str, sources: list[dict]) -> bytes:
    """
    Generate a whitepaper-style PDF and return raw bytes.

    Parameters
    ----------
    topic   : research topic string
    report  : markdown report text
    sources : list of {"title": ..., "url": ...}
    """
    buf = io.BytesIO()
    styles = _build_styles()

    # Document with header/footer page template
    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
    )
    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="main",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame],
                                       onPage=_header_footer)])

    story = []

    # ── Cover / Title block ───────────────────────────────────────────────────
    story.append(Spacer(1, 12 * mm))
    story.append(Paragraph("INQUIRA AI", ParagraphStyle(
        "brand", fontName="Helvetica-Bold", fontSize=10,
        textColor=INQ_ACCENT, spaceAfter=4 * mm,
    )))
    story.append(Paragraph(topic, styles["title"]))
    story.append(Paragraph("Automated Multi-Agent Research Report", styles["subtitle"]))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}",
        styles["meta"],
    ))
    story.append(HRFlowable(width="100%", thickness=1.5, color=INQ_BLUE,
                             spaceAfter=8 * mm))

    # ── Report body ───────────────────────────────────────────────────────────
    story.extend(_md_to_flowables(report, styles))

    # ── Sources / References ──────────────────────────────────────────────────
    if sources:
        story.append(Spacer(1, 8 * mm))
        story.append(Paragraph("Sources & References", styles["h2"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=INQ_BORDER,
                                 spaceAfter=3 * mm))

        for i, src in enumerate(sources, 1):
            title = src.get("title", "Untitled") or "Untitled"
            url = src.get("url", "") or ""
            story.append(KeepTogether([
                Paragraph(f"[{i}] {title}", styles["source_title"]),
                Paragraph(
                    f'<a href="{url}" color="#2563EB">{url}</a>',
                    styles["source_link"],
                ),
                Spacer(1, 1 * mm),
            ]))

    doc.build(story)
    return buf.getvalue()